# Liquibase Properties
changeLogFile=changelog/db.changelog-master.xml
url=jdbc:postgresql://localhost:15432/appone_db
username=appone_user
password=appone_password
driver=org.postgresql.Driver
liquibase.hub.mode=off

